# 认证服务器地址
server:
  port: 80

logging:
  level.root: INFO
  level.org.apache.dubbo: WARN
  level.com.alibaba.cloud: WARN
  level.org.springframework.web.reactive: DEBUG
  file:
    max-size: 256MB
    name: ${user.home}/work/logs/aupup/client2.log

spring:
  session:
    store-type: none
  main:
    allow-bean-definition-overriding: true